name: designthinking
favicon: null
layout_spectrum: 0.7140015487093478
typography_spectrum: 0.8878295170143247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2861053957603872
  lightness: 0.19478090410120785
  saturation: 0.2662562089972198
  rhythmicContrast: 0.25171648943796754
purpose: []
